spring.application.name=engineer-registry
spring.datasource.url=jdbc:postgresql://localhost:5332/engineer_registry
spring.datasource.username=malik
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
